config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "static_pages#home"
  get "/about", to: "static_pages#about"
  get "/projects", to: "static_pages#projects"
  get "/admin", to: "posts#admin"
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post

    validates :author_name, presence: true, length: {maximum: 50}
    validates :body, presence: true, length: {maximum: 250}
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    def index
      
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "bribrah", password: "people46", only: [:destroy]
    
    def create
        @comment = Comment.new(comment_params)
        @comment.post_id = params[:post_id]
        if @comment.save
            flash[:success] = "Comment created successfully"
            redirect_to post_path(@comment.post)
        else
            flash.now[:warning] = "comment not created successfully"
            params[:id] = @comment.post_id
            render "posts/show"
        end
    end

    def destroy
        @comment = Comment.find(params[:id])
        post_id = params[:post_id]
        if @comment.destroy
            flash[:success] = 'Comment was successfully deleted.'
            redirect_to post_path(post_id)
        else
            flash[:error] = 'Something went wrong'
            redirect_to comments_url
        end
    end
    

    private
    def comment_params
        params.require(:comment).permit(:author_name, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  http_basic_authenticate_with name: "bribrah", password: "people46", except: [:index, :show]

      
    def index
      @posts = Post.all
    end
    def new
      @post = Post.new
    end
    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to @post
      else
        render new
      end
    end

    def admin
      @posts = Post.all
    end
    def new
      @post = Post.new
    end
    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to @post
      else
        render new
      end
    end

    def show
      @post = Post.find(params[:id])
      @comment = Comment.new
      @comment.post_id = @post_id
    end

    def edit
      @post = Post.find(params[:id])
    end

    def update
      @post = Post.find(params[:id])
        if @post.update_attributes(post_params)
          flash[:success] = "Post was successfully updated"
          redirect_to @post
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end
    
 
  
    def destroy
      @post = Post.find(params[:id])
      if @post.destroy
        flash[:success] = 'Post was successfully deleted.'
        redirect_to posts_url
      else
        flash[:error] = 'Something went wrong'
        redirect_to posts_url
      end
    end
    
    
    
    





    private
    def post_params
      params.require(:post).permit(:title,:text)
    end

    
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
    
    def about
    end



    def projects
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    #defines the title of a page
    def page_title(page_title = "")
        base_title = "Coding Noob"
        if page_title.empty?
            base_title
        else
            base_title + " | " + page_title
        end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/comments/_errors.html.erb
<% if @comment.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            Your comment had <%= pluralize(@comment.errors.count, "error") %>
        </div>
        <ul>
            <% @comment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<div class="form-group">

    <%= form_for [@post, @comment] do |f| %>
    <%= render partial: 'comments/errors', object: @comment %>
        <div class="comment-form">
            <%= f.label :author_name, "Your Name" %> <br />
            <div class="row">
                <div class="col-lg-3">
                    <%= f.text_field :author_name, class: "form-control"%>
                </div>
            </div>
        </div>
        <div class="comment-form">
            <%= f.label :body, "Your Comment" %> <br />
            <%= f.text_area :body, class: "form-control" %>   
        </div>
        <%= f.submit 'Submit', class: "btn btn-light"%>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The Coding Noob Blog by Brian Espinosa
    </small>

    <nav>
        <ul>
            <li><strong>Email:</strong>  brianthecodingnoob@gmail.com</li>
            <li><strong>Github:</strong> <a href="https://github.com/bribrah">https://github.com/bribrah</a></li>
        </ul>
    </nav>
</footer>

app/views/layouts/_head.html.erb
<title><%=  page_title(yield(:title)) %> </title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<meta name="description" content="<%= (yield(:title)) %>">
<meta name="author" content="Brian Espinosa">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

app/views/layouts/_navbar.html.erb
<nav class = "navbar navbar-fixed-top navbar-inverse">
    <div class = "container-fluid">
            <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                      <span class="icon-bar"></span>
                    </button>
         <%= link_to  "Coding Noob", root_path, id: "logo" %>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-1">

                <ul class="nav navbar-nav navbar-right ">
                    <li><%= link_to  "Home", root_path %></li>
                    <li><%= link_to  "Blog", posts_path %></li>
                    <li><%= link_to  "About me", about_path %></li>
                    <li><%= link_to  "My Projects", projects_path %></li>
                </ul>
            </div>
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render  "layouts/head" %>
  </head>

  <body>
    <%= render  "layouts/navbar" %>
    <div class="container">
        <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"> <%= message %></div>
      <% end %>
      <%= yield %>
      <%= render  "layouts/footer" %>
  </div>
  </body>
</html>

app/views/posts/_comment.html.erb
<div class="well">
        <div class="page-header" style="margin-top: 5px">
            <h3 style="margin-top: 5px">Comment by <%= comment.author_name %>
                <%= link_to  [comment.post, comment], method: :delete, data:{ confirm: "Are you Sure?"} do%>
                    <span style="float:right; font-size: .5em;"> Delete comment</span> </h3>
                <% end%>
            <p class="small" style="margin-top: 5px;">Posted <%= distance_of_time_in_words(comment.created_at,DateTime.now) %> ago</p>
        </div>
        <p class="comment-body"><%= comment.body %></p>
    </div>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <%= @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
  </div>
  <div>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :text %>
  </div>
  <div>
    <%= f.cktext_area :text, rows: 10 %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/admin.html.erb
<% provide(:title, "Admin Panel") %>
<h1 class="page-header">Admin Panel</h1>
<%  @posts.order(:id).each do |post| %>
<div class="row">
    <div class="post_title">
        <div class="btn btn-primary">
            <%= link_to  post.title, post_path(post) %> 
            <span class="badge"><%= post.comments.count %></span>
        </div>
    </div>
    <span class="label label-default">
        <%= post.created_at.to_formatted_s :long_ordinal %>
    </span>
        <%= link_to  "Edit Post", edit_post_path(post), class:'btn btn-primary'%>
        <%= link_to  "Delete Post", post_path(post), method: :delete, data:{ confirm: "Are you Sure?"}, class:'btn btn-primary'%>
</div>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 <%= render 'form' %> 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% provide(:title, "Blog Index") %>
<h1 class="page-header">Blog posts</h1>
<div class="post-links">
<%  @posts.order(:id).each do |post| %>
<div class="post-link">
    <% nokogiri_html_string = Nokogiri::HTML(post.text) %>
    <% image_tag = nokogiri_html_string.css('img').first%>
    <% image_src = image_tag.attributes['src']%>
    <%= link_to  post_path(post) do %>
        <img src="<%= image_src %>" alt="">
        <div class="post-link-caption">
            <%= post.title %>
            <span class="badge"><%= post.comments.count %></span>
            <span class="label label-default">
                <%= post.created_at.to_formatted_s :long_ordinal %>
            </span>
        </div>
        <% end%>
</div>
        <% end %>
    </div>
        

app/views/posts/new.html.erb
<h1>New Article</h1>
<%= render 'form' %>
<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% @post = Post.find(params[:id])%>
<% provide(:title, @post.title)%>
<h1 class="page-header"><%= @post.title %></h1>
<div class="container-fluid blog-post">
    <%= raw(@post.text) %>
</div>
<div class="bottom-buttons">
    <p><%= link_to  "<-- Back to Index", posts_path, class: "btn btn-primary" %></p>
</div>

<h3 class="page-header">Comments (<%= @post.comments.size %>)</h3>
<%= render partial: 'posts/comment', collection: @post.comments %>
<%= render partial: 'comments/form' %>
<script>
    if ( /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)){
        const allImages = document.querySelectorAll('img');
        console.log(window.innerWidth)
        allImages.forEach(image => {
            console.log(image.width);
            image.style.width = `${.5 * image.width}px`;
            image.style.height = 'auto';
            console.log(image.width);
            console.log(image.height)
        })
        const topImage = document.querySelector('img');
        console.log("test")
        topImage.style.width = '100%';
        topImage.style.height = 'auto';
    }
if (typeof javascriptHeader == "undefined"){
    let javascriptHeader
    let text
}
    javascriptHeader  = document.querySelector('.javascriptHeader');
    text = javascriptHeader.querySelector('h1');
    text.offsetParent = javascriptHeader;
    if (javascriptHeader){
        javascriptHeader.addEventListener('mousemove',shadow);
        const walk = 200;
        const width = javascriptHeader.offsetWidth;
        const height = javascriptHeader.offsetHeight;

        function shadow(e){
            let {offsetX: x, offsetY: y} = e;
            if (this !== e.target){
                y =y + e.target.offsetTop;
            }

            const xWalk = (x / width * walk) - (walk / 2)
            const yWalk = (y / height * walk) - (walk / 2)
            text.style.textShadow = `${xWalk}px ${yWalk}px 0 blue`


        }
    }
</script>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1 class="with_subtext">About Me</h1>
<i class="fas fa-subscript center">AKA How I leanrned to stop worrying (about becoming a doctor) and
    love the code.</i>
<img src="" class="img-fluid ${3|rounded-top,rounded-right,rounded-bottom,rounded-left,rounded-circle,|}" alt="">
<%= image_tag "pt_reyes.jpg", :class => "img-fluid center", :style => "display: block; margin: auto; width: 75%; margin-bottom: 30px;"  %>
<p>
    My name is Brian Espinosa and I am an ex pre-med student turned software engineer ambitioner/student. I originally had a goal of joining the medical field, and was all set and ready to do it. I had got a 3.5 in college in a tough major, I scored in the 98 percentile on my MCAT, and I had spent time volunteering. Then after all of that, I finally came to accept that I do not want to be a doctor, as it has never really been my passion. Computers and technology on the other hand I love and always have.

</p>
<p>
    I built my first computer when I was 11 years old and spent basically my entire life with that same computer, just upgrading it along the way. I spent way too much time sitting on that computer as a kid. I tinkered in everything. I installed OS x on it, ubuntu, ran a World of Warcraft private server for awhile. Anyways, the point is, I freaking love computers and it has taken me this long to finally to the realization that I want to spend my life studying and building stuff for them. So here I am deciding to write a blog about my journey into the field. I decided to do this not only so I had a reason to reflect on what I learned, but because I know that it is very stressful not knowing what to do in life and how hard it can be making a career switch.
</p>

app/views/static_pages/home.html.erb
<div class="jumbotron center">
    <h1 class="display-3">Coding Noob Blog</h1>
    <p class="lead">Sharing my Journey from Coding Noob to Coding Savvy to Help you on your own Quest!</p>
    <hr class="my-2">
    
    
    
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        
        <div class="carousel-inner">
            <% firstPost = false%>
            <% n = 1%>
            <% Post.order(:created_at).reverse.each do |post| %>
            <% nokogiri_html_string = Nokogiri::HTML(post.text) %>
            <% image_tag = nokogiri_html_string.css('img').first%>
            <% image_src = image_tag.attributes['src']%>
            
            
            <% if !firstPost %>
            <div class="item active">
                <a href=<%=  post_path(post)%>>
                    <img class="carousel-image" src="<%= image_src %>" alt="">
                    <div class="carousel-caption">
                        <h3><%= post.title %></h3>
                    </div>
                </a>
            </div>
            <%  firstPost = true%>
            <% else %>
            <div class="item">
                <a href=<%=  post_path(post)%>>
                    <img class="carousel-image" src="<%= image_src %>" alt="">
                    <div class="carousel-caption">
                        <h3><%= post.title %></h3>
                    </div>
                </a>
            </div>
            <% end%>
            <% if n == 3%>
            <% break %>
            <% end %>
            <% n = n+1%>
            <% end%>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    
    
    
    <p class="center">Created by <a href="https://www.linkedin.com/in/brian-espinosa-611592172/">Brian Espinosa</a></p>
    <p class="lead">
        <%= link_to  "Checkout the Blog!", posts_path, class: "btn btn-lg btn-primary" %>
    </p>
    <script>
        const carouselContainer = document.querySelector(".carousel");
        const carouselImages = document.querySelectorAll('.carousel-image');
        carouselImages.forEach(image => {
            image.style.height = `${carouselContainer.offsetHeight}px`;
            image.style.width = `${carouselContainer.offsetWidth}px`;
            console.log(image.style.height);
        })


    </script>
</div>

app/views/static_pages/projects.html.erb
<% provide(:title, "Projects") %>
<h1 class="project" style="margin-bottom: 4px;">My Projects</h1>
<h3 class="center"><a href="https://github.com/bribrah">Github Profile</a></h3>

<div class="project">
<h2 >Burnout Battle (java)</h2>
<img src="/images/burnoutbattle.png"  alt="java-lightcycle-game">
<p>This is a Tron like lightcycle game where the objective is to run the player off the map or to collect the dots (if single-player)The project was completed as the final for my introduction to Java course. It mostly utilized the swing and the graphics libraries of java. You can check out the source code on <a href="https://github.com/bribrah/Java-Final-Project">github</a>. There is also a runnable jar in the repository if you would like to take it for a spin.
</p>
</div>
<div class="project">
    <h2><a href="http://jamminmovies.com/">Jammin Movies (JS/CSS/HTML/Python)</a></h2>
    <img src="/images/jammin-movies.png" alt="">
    <p>
        This is a website I built for my girlfriend and I to keep track of the movies we are watching.
        It also has a built in random movie picker because that is how we usually pick what movie to watch.
        The project uses the firebase database for storage and integrates in a lot of different javascript and css
        concepts. Also utilizes the BeautifulSoup4 python module to webscrape the libraries of all three major
        streaming services and display which movies on the list are streamable. It also supports user accounts
        and organization by integrating the firebase integration system. The app is fully written using only
        vanilla JS and is hosted for free on github pages.
    </p>
</div>
<div class="project">
    <h2><a href="https://bribrah.github.io/JS-30/index.html">JS 30 (Javascript)</a></h2>
    <img src="/images/js30 collage.png" alt="">
    <p>
        JS30 is an online course that teaches general JS, HTML, and CSS. It a collection of 30 projects that 
        teach a variety of Javascript and CSS practices. Click the link above to be taken to my index of JS30 
        projects that I have completed!
    </p>
</div>


<div class="project">
    <h2> <a href="https://brians-sample-app.herokuapp.com/"> Rails Sample App (Ruby on Rails)</a></h2>
    <p>
        This is a website I created using online tutorials. The website supports custom users and account creation, posts, and user profile customization. The site is still a work in progress, but I have learned about cookies, authentication, secure practices that pertain to rails and web development, among many many other things. Final website will function as a twitter like clone.
    </p>
</div>


<div class="project">
    <h2 ><a href="https://bribrah.github.io/calculator/">Calculator (Javascript)</a></h2>
    <img src="/images/calculator_project.png" alt="calculator">
    <p>
        A simple javascript calculator with all the basic functions. This was my first challenging javascript project, and also utilized html/css/web-design skills. The source code can be found on my <a href="https://github.com/bribrah/calculator">github</a> and you can view the web-app by following the link above.</a>.
    </p>
</div>
    

<div class="project">
    <h2 ><a href="https://brianshangman.herokuapp.com">Hangman (Sinatra/Ruby)</a></h2>
    <img src="/images/hangman.png" alt="hangman">
    <p>
        A sinatra framework/ruby based hangman game. First backend project I had in ruby and first real web app hosting with a ruby framework. Also utilized web-design/css/html concepts. The web app can be viewed/played by following the link above.</a>.
    </p>
</div>

<div class="project">
    <h2 >This Website (Ruby on Rails)</h2>
    <p>
        This website was created using the Ruby on Rails framework and does not use any type of blog or web engine. It is my first real Ruby on Rails app and I intend to continually improve the design and add more features as time goes on!
    </p>
</div>
<script>
        if ( /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent)){
            const images = document.querySelectorAll('img');
            console.log("test")
            images.forEach(image =>{
                image.style.width = '100%';
                image.style.height = 'auto';
            })
        }
</script>